from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import inch
from io import BytesIO
from datetime import datetime

class PDFExporter:
    """
    JMc - 2026-03-15 - Exporter service for generating printable PDF ticket sheets.
    Because if you're going to play a syndicate, you need the receipts to keep the greedy 
    neighbors in line.
    """

    @staticmethod
    def generate_ticket_pdf(batch_name: str, tickets: list, created_at: datetime):
        buffer = BytesIO()
        p = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter

        # Header
        p.setFont("Helvetica-Bold", 24)
        p.setFillColor(colors.HexColor("#3b82f6")) # Oracle Blue
        p.drawString(inch, height - inch, "ORACLE DEPLOYMENT MANIFEST")
        
        p.setFont("Helvetica", 10)
        p.setFillColor(colors.black)
        p.drawString(inch, height - 1.3 * inch, f"Batch: {batch_name}")
        p.drawString(inch, height - 1.5 * inch, f"Deployment Sequence: {created_at.strftime('%Y-%m-%d %H:%M:%S')}")
        p.drawString(inch, height - 1.7 * inch, f"Total Combinations: {len(tickets)}")

        # Draw a line
        p.setStrokeColor(colors.lightgrey)
        p.line(inch, height - 1.9 * inch, width - inch, height - 1.9 * inch)

        # Ticket Table
        y = height - 2.3 * inch
        p.setFont("Helvetica-Bold", 12)
        p.drawString(inch, y, "SLOT")
        p.drawString(2 * inch, y, "PRIMARY NUMBERS")
        p.drawString(5.5 * inch, y, "SPECIAL")
        
        y -= 0.3 * inch
        p.line(inch, y + 0.1 * inch, width - inch, y + 0.1 * inch)

        p.setFont("Courier-Bold", 14)
        for i, ticket in enumerate(tickets):
            if y < inch: # Page break logic
                p.showPage()
                y = height - inch
                p.setFont("Courier-Bold", 14)

            # Draw slot index
            p.setFillColor(colors.grey)
            p.setFont("Helvetica", 10)
            p.drawString(inch, y, f"#{i+1:03}")
            
            # Draw White Balls
            p.setFillColor(colors.black)
            p.setFont("Courier-Bold", 14)
            white_balls_str = "  ".join([str(b).zfill(2) for b in ticket['white_balls']])
            p.drawString(2 * inch, y, white_balls_str)
            
            # Draw Special Ball
            if ticket['special_ball'] is not None:
                p.setFillColor(colors.HexColor("#3b82f6"))
                p.drawString(5.5 * inch, y, str(ticket['special_ball']).zfill(2))
            
            y -= 0.4 * inch
            p.setStrokeColor(colors.whitesmoke)
            p.line(inch, y + 0.1 * inch, width - inch, y + 0.1 * inch)

        # Footer
        p.setFont("Helvetica-Oblique", 8)
        p.setFillColor(colors.grey)
        p.drawString(inch, 0.5 * inch, "Generated by Lottery Oracle v1.0 - Combinatorial Matrix Analysis")
        p.drawRightString(width - inch, 0.5 * inch, f"Verified: {created_at.strftime('%Y-%m-%d %H:%M:%S')}")

        p.showPage()
        p.save()

        buffer.seek(0)
        return buffer
